# DV1597 - Assignment 2

### Maximilian Carlbäck - maco24@student.bth.se

### Adam Block - ...@student.bth.se

Initialize data

In [19]:
import pandas as pd

df_C19_daily_number_cases = pd.read_csv('1.COVID-19_daily_number_of_new_cases_and_deaths.csv')

df_C19_vaccination = pd.read_csv('2.COVID-19_vaccination.csv')

df_C19_hospital_ICU = pd.read_csv('3.COVID-19_hospital_and_ICU_admission_rates.csv')

# print(df_C19_daily_number_cases.head())
# print(df_C19_vaccination.head())
# print(df_C19_hospital_ICU.head())

In [20]:
print(len(df_C19_daily_number_cases))
df_C19_daily_number_cases_nodupes = df_C19_daily_number_cases.drop_duplicates()
print(len(df_C19_daily_number_cases_nodupes))

print(len(df_C19_vaccination))
df_C19_vaccination_nodupes = df_C19_vaccination.drop_duplicates()
print(len(df_C19_vaccination_nodupes))

print(len(df_C19_hospital_ICU))
df_C19_hospital_ICU_nodupes = df_C19_hospital_ICU.drop_duplicates()
print(len(df_C19_hospital_ICU_nodupes))

28729
28729
681330
681330
25100
25100

In [21]:
df_C19_daily_number_cases["dateRep"] = pd.to_datetime(df_C19_daily_number_cases["dateRep"])
neg = df_C19_daily_number_cases[df_C19_daily_number_cases["cases"]<0] 
neg
#ööljk

C:\Users\maxec\AppData\Local\Temp\ipykernel_27624\1052373712.py:1: UserWarning:

Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2020,continentExp
3983,2022-01-21,21,1,2022,-3203.0,3.0,Cyprus,CY,CYP,888005,Europe
6209,2021-03-24,24,3,2021,-2001.0,8.0,Denmark,DK,DNK,5822763,Europe
9120,2021-05-20,20,5,2021,-348846.0,133.0,France,FR,FRA,67320216,Europe
9472,2020-06-02,2,6,2020,-766.0,107.0,France,FR,FRA,67320216,Europe
9599,2020-01-27,27,1,2020,-3.0,0.0,France,FR,FRA,67320216,Europe
11205,2021-02-21,21,2,2021,-2859.0,0.0,Greece,EL,GRC,10718565,Europe
12890,2021-10-04,4,10,2021,-968.0,0.0,Iceland,IS,ISL,364134,Europe
13469,2022-06-09,9,6,2022,-228.0,0.0,Ireland,IE,IRL,4964440,Europe
13583,2022-02-15,15,2,2022,-5532.0,17.0,Ireland,IE,IRL,4964440,Europe
13749,2021-09-02,2,9,2021,-1707.0,0.0,Ireland,IE,IRL,4964440,Europe
14064,2020-10-22,22,10,2020,-12.0,3.0,Ireland,IE,IRL,4964440,Europe
15157,2020-06-19,19,6,2020,-148.0,47.0,Italy,IT,ITA,59641488,Europe
18140,2020-03-20,20,3,2020,-41.0,0.0,Lithuania,LT,LTU,2794090,Europe
19962,2020-08-16,16,8,2020,-42.0,0.0,Malta,MT,MLT,514564,Europe

Vi antar att deaths är 0 när det är NaN värde för att de kringliggande värdena är nära 0

In [22]:

df_C19_daily_number_cases["deaths"] = df_C19_daily_number_cases["deaths"].fillna(0)

Vi såg att spanien bara rapporterade var tredje dag (isch) så vi satte alla NaN värden i "cases" kolumnen till 0

In [23]:
df_C19_daily_number_cases.loc[
    (df_C19_daily_number_cases["geoId"] == "ES") &
    (df_C19_daily_number_cases["cases"].isna()),
    "cases"
] = 0

print(df_C19_daily_number_cases[(df_C19_daily_number_cases["geoId"] == "ES") & (df_C19_daily_number_cases["cases"].isna())])

Empty DataFrame
Columns: [dateRep, day, month, year, cases, deaths, countriesAndTerritories, geoId, countryterritoryCode, popData2020, continentExp]
Index: []

Vi såg också att NaN värdena på "cases" på Island verkade inte vara borttappade värden utan snarare ackummulerade, då efter dagar av NaN värde kom ett mycket större värde ochs sedan tillbaka till det "normala". Vi satte också alla dessa värden till 0

In [24]:
df_C19_daily_number_cases.loc[
    (df_C19_daily_number_cases["geoId"] == "IS") &
    (df_C19_daily_number_cases["cases"].isna()),
    "cases"
] = 0

print(df_C19_daily_number_cases[(df_C19_daily_number_cases["geoId"] == "IS") & (df_C19_daily_number_cases["cases"].isna())])

Empty DataFrame
Columns: [dateRep, day, month, year, cases, deaths, countriesAndTerritories, geoId, countryterritoryCode, popData2020, continentExp]
Index: []

Detsamma som Island gäller Danmark

In [25]:
df_C19_daily_number_cases.loc[
    (df_C19_daily_number_cases["geoId"] == "DK") &
    (df_C19_daily_number_cases["cases"].isna()),
    "cases"
] = 0

print(df_C19_daily_number_cases[(df_C19_daily_number_cases["geoId"] == "DK") & (df_C19_daily_number_cases["cases"].isna())])

Empty DataFrame
Columns: [dateRep, day, month, year, cases, deaths, countriesAndTerritories, geoId, countryterritoryCode, popData2020, continentExp]
Index: []

Vi sätter Estonia och Norway till 0 också

In [26]:
df_C19_daily_number_cases.loc[
    (df_C19_daily_number_cases["geoId"] == "EE") &
    (df_C19_daily_number_cases["cases"].isna()),
    "cases"
] = 0

print(df_C19_daily_number_cases[(df_C19_daily_number_cases["geoId"] == "EE") & (df_C19_daily_number_cases["cases"].isna())])

df_C19_daily_number_cases.loc[
    (df_C19_daily_number_cases["geoId"] == "NO") &
    (df_C19_daily_number_cases["cases"].isna()),
    "cases"
] = 0 

print(df_C19_daily_number_cases[(df_C19_daily_number_cases["geoId"] == "NO") & (df_C19_daily_number_cases["cases"].isna())])

Empty DataFrame
Columns: [dateRep, day, month, year, cases, deaths, countriesAndTerritories, geoId, countryterritoryCode, popData2020, continentExp]
Index: []
Empty DataFrame
Columns: [dateRep, day, month, year, cases, deaths, countriesAndTerritories, geoId, countryterritoryCode, popData2020, continentExp]
Index: []

In [27]:
print(df_C19_daily_number_cases[df_C19_daily_number_cases["cases"].isnull()])
# print(df_C19_daily_number_cases[df_C19_daily_number_cases["geoId"] == "DK"])

Empty DataFrame
Columns: [dateRep, day, month, year, cases, deaths, countriesAndTerritories, geoId, countryterritoryCode, popData2020, continentExp]
Index: []

In [28]:
print(df_C19_daily_number_cases)

         dateRep  day  month  year    cases  deaths countriesAndTerritories  \
0     2022-10-23   23     10  2022   3557.0     0.0                 Austria
1     2022-10-22   22     10  2022   5494.0     4.0                 Austria
2     2022-10-21   21     10  2022   7776.0     4.0                 Austria
3     2022-10-20   20     10  2022   8221.0     6.0                 Austria
4     2022-10-19   19     10  2022  10007.0     8.0                 Austria
...          ...  ...    ...   ...      ...     ...                     ...
28724 2020-02-08    8      2  2020      0.0     0.0                  Sweden
28725 2020-02-07    7      2  2020      0.0     0.0                  Sweden
28726 2020-02-06    6      2  2020      0.0     0.0                  Sweden
28727 2020-02-05    5      2  2020      0.0     0.0                  Sweden
28728 2020-02-04    4      2  2020      1.0     0.0                  Sweden

      geoId countryterritoryCode  popData2020 continentExp
0        AT                  AUT      8901064       Europe
1        AT                  AUT      8901064       Europe
2        AT                  AUT      8901064       Europe
3        AT                  AUT      8901064       Europe
4        AT                  AUT      8901064       Europe
...     ...                  ...          ...          ...
28724    SE                  SWE     10327589       Europe
28725    SE                  SWE     10327589       Europe
28726    SE                  SWE     10327589       Europe
28727    SE                  SWE     10327589       Europe
28728    SE                  SWE     10327589       Europe

[28729 rows x 11 columns]

# 3.2

In [62]:
import plotly.express as px

# Make sure dateRep is datetime
df_C19_daily_number_cases["dateRep"] = pd.to_datetime(df_C19_daily_number_cases["dateRep"], dayfirst=True, errors="coerce")

# Create year column
df_C19_daily_number_cases["year"] = df_C19_daily_number_cases["dateRep"].dt.year

# Keep only 2020, 2021 and 2022
df_filtered = df_C19_daily_number_cases[df_C19_daily_number_cases["year"].isin([2020, 2021, 2022])]

# Group by country and year
df_country_year = df_filtered.groupby(["year", "countriesAndTerritories", "countryterritoryCode"],as_index=False)[["cases", "deaths"]].sum()

fig_cases = px.choropleth(
    df_country_year,
    locations="countryterritoryCode",
    color="cases",
    hover_name="countriesAndTerritories",
    animation_frame="year",
    range_color=(0, max(df_country_year["cases"])),
    color_continuous_scale=px.colors.sequential.YlOrRd,
    title="Total COVID-19 Cases by Country in 2020, 2021 and 2022",
    width=800,
    height=600
)

fig_cases.update_layout(
    geo=dict(scope="europe", resolution=50)
)

fig_cases.show()

fig_deaths = px.choropleth(
    df_country_year,
    locations="countryterritoryCode",
    color="deaths",
    hover_name="countriesAndTerritories",
    animation_frame="year",
    range_color=(0, max(df_country_year["deaths"])),
    color_continuous_scale=px.colors.sequential.Reds,
    title="Total COVID-19 Deaths by Country in 2020, 2021 and 2022",
    width=800,
    height=600
)

fig_deaths.update_layout(
    geo=dict(scope="europe", resolution=50)
)

fig_deaths.show()

# Cleaning vaccination data

In [43]:
# print(df_C19_vaccination)

null_info = df_C19_vaccination.isnull()

df_C19_vaccination[null_info.any(axis=1)]

,YearWeekISO,ReportingCountry,Denominator,NumberDosesReceived,NumberDosesExported,FirstDose,FirstDoseRefused,SecondDose,DoseAdditional1,DoseAdditional2,DoseAdditional3,DoseAdditional4,DoseAdditional5,UnknownDose,Region,TargetGroup,Vaccine,Population
15972,2022-W38,BE,596219.0,NaN,NaN,1,0.0,0,4,1477,33,0,0,0,BE,HCW,MOD,11617623
15973,2022-W38,BE,NaN,NaN,NaN,0,0.0,0,0,0,0,0,0,0,BE,AgeUNK,MOD,11617623
15974,2022-W38,BE,647589.0,NaN,NaN,3,0.0,0,1,31,119,0,0,0,BE,Age80+,MOD,11617623
15975,2022-W38,BE,948982.0,NaN,NaN,2,0.0,0,0,66,24,0,0,0,BE,Age70_79,MOD,11617623
15976,2022-W38,BE,1367705.0,NaN,NaN,1,0.0,1,1,258,12,0,0,0,BE,Age60_69,MOD,11617623
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
681258,2021-W23,SK,NaN,0.0,0.0,0,0.0,1,0,0,0,0,0,0,SK,AgeUNK,MOD,5459781
681280,2021-W24,SK,NaN,0.0,0.0,3,0.0,4,0,0,0,0,0,0,SK,AgeUNK,COM,5459781
681297,2021-W24,SK,NaN,0.0,0.0,1,0.0,0,0,0,0,0,0,0,SK,AgeUNK,SPU,5459781
681312,2021-W25,SK,NaN,0.0,0.0,14,0.0,7,0,0,0,0,0,0,SK,AgeUNK,COM,5459781
681325,2021-W25,SK,NaN,0.0,0.0,2,0.0,0,0,0,0,0,0,0,SK,AgeUNK,MOD,5459781

In [64]:
print(df_C19_vaccination[df_C19_vaccination["Vaccine"].isnull()])

print(df_C19_vaccination[df_C19_vaccination["TargetGroup"].isna()])

print(df_C19_vaccination[df_C19_vaccination["ReportingCountry"].isna()])

Empty DataFrame
Columns: [YearWeekISO, ReportingCountry, Denominator, NumberDosesReceived, NumberDosesExported, FirstDose, FirstDoseRefused, SecondDose, DoseAdditional1, DoseAdditional2, DoseAdditional3, DoseAdditional4, DoseAdditional5, UnknownDose, Region, TargetGroup, Vaccine, Population]
Index: []
Empty DataFrame
Columns: [YearWeekISO, ReportingCountry, Denominator, NumberDosesReceived, NumberDosesExported, FirstDose, FirstDoseRefused, SecondDose, DoseAdditional1, DoseAdditional2, DoseAdditional3, DoseAdditional4, DoseAdditional5, UnknownDose, Region, TargetGroup, Vaccine, Population]
Index: []
Empty DataFrame
Columns: [YearWeekISO, ReportingCountry, Denominator, NumberDosesReceived, NumberDosesExported, FirstDose, FirstDoseRefused, SecondDose, DoseAdditional1, DoseAdditional2, DoseAdditional3, DoseAdditional4, DoseAdditional5, UnknownDose, Region, TargetGroup, Vaccine, Population]
Index: []

In [ ]:
df_C19_vaccination["FirstDoseRefused"] = df_C19_vaccination["FirstDoseRefused"].fillna(0)

print(df_C19_vaccination[df_C19_vaccination["FirstDoseRefused"].isna()])

Empty DataFrame
Columns: [YearWeekISO, ReportingCountry, Denominator, NumberDosesReceived, NumberDosesExported, FirstDose, FirstDoseRefused, SecondDose, DoseAdditional1, DoseAdditional2, DoseAdditional3, DoseAdditional4, DoseAdditional5, UnknownDose, Region, TargetGroup, Vaccine, Population]
Index: []

# 3.3

In [58]:
# Rank top 3 most used vaccines

vaccine_counts = df_C19_vaccination["Vaccine"].value_counts()
top_3_vaccines = vaccine_counts.head(3)
print(top_3_vaccines)

# Rank top 3 most used vaccines per country

pd.set_option("display.max_rows", None)

vaccine_counts_per_country = df_C19_vaccination.groupby("ReportingCountry")["Vaccine"].value_counts()
top_3_vaccines_per_country = vaccine_counts_per_country.groupby("ReportingCountry").head(3)
print(top_3_vaccines_per_country)

Vaccine
COM      104833
MOD      100023
JANSS     92435
Name: count, dtype: int64
ReportingCountry  Vaccine
AT                AZ            1452
                  COM           1452
                  COMBA.1       1452
BE                COM           1321
                  MOD           1271
                  JANSS         1121
BG                COM           1298
                  MOD           1297
                  AZ            1247
CY                COM           1361
                  AZ            1130
                  MOD           1108
CZ                COM           1530
                  MOD           1316
                  JANSS          825
DE                UNK            480
DK                COM           1382
                  MOD           1117
                  JANSS          637
EE                COM           1135
                  MOD           1090
                  AZ            1058
EL                COM           2029
                  COMBA.4-5     1964
                  JANSS         1964
ES                AZ            1800
                  COM           1800
                  COMBIV        1800
FI                AZ           38064
                  COM          38064
                  COMBA.1      38064
FR                UNK          19602
                  AZ             121
                  COM            121
HR                COM           1440
                  MOD           1425
                  JANSS         1335
HU                COM           1210
                  MOD           1180
                  BECNBG        1130
IE                COM           1547
                  MOD           1021
                  AZ             695
IS                COM           1652
                  JANSS          871
                  MOD            803
IT                COM           3546
                  MOD           2932
                  JANSS         1704
LI                COM           1190
                  MOD           1190
                  JANSS         1040
LT                COM           2057
                  MOD           2006
                  AZ            1938
LU                COM           1464
                  MOD           1428
                  AZ            1392
LV                COM           1258
                  MOD           1015
                  JANSS          812
MT                COM           1285
                  AZ            1260
                  MOD           1231
NL                AZ             990
                  COM            990
                  JANSS          990
NO                COM           1087
                  MOD            949
                  AZ             582
PL                AZ           26962
                  COM          26962
                  JANSS        26962
PT                COM           2178
                  MOD           1597
                  AZ            1443
RO                COM           1273
                  MOD           1263
                  AZ            1164
SE                AZ            1936
                  COM           1936
                  MOD           1936
SI                COM           1001
                  MOD            716
                  AZ             375
SK                COM           1264
                  MOD            807
                  JANSS          595
Name: count, dtype: int64

For the most part COM is the most used vaccine in every country.

# 3.4

In [ ]:
filtered_df = df_C19_vaccination[df_C19_vaccination["Vaccine"].isin(["COM", "MOD", "JANSS"])]

print(main_target_group_per_country_vaccine.to_string(index=False))

    ReportingCountry TargetGroup Vaccine  count
0                 AT         ALL     COM    121
1                 AT         ALL   JANSS    121
2                 AT         ALL     MOD    121
3                 AT      Age0_4     COM    121
4                 AT      Age0_4   JANSS    121
5                 AT      Age0_4     MOD    121
6                 AT    Age10_14     COM    121
7                 AT    Age10_14   JANSS    121
8                 AT    Age10_14     MOD    121
9                 AT    Age15_17     COM    121
10                AT    Age15_17   JANSS    121
11                AT    Age15_17     MOD    121
12                AT    Age18_24     COM    121
13                AT    Age18_24   JANSS    121
14                AT    Age18_24     MOD    121
15                AT    Age25_49     COM    121
16                AT    Age25_49   JANSS    121
17                AT    Age25_49     MOD    121
18                AT    Age50_59     COM    121
19                AT    Age50_59   JANSS    121
20                AT    Age50_59     MOD    121
21                AT      Age5_9     COM    121
22                AT      Age5_9   JANSS    121
23                AT      Age5_9     MOD    121
24                AT    Age60_69     COM    121
25                AT    Age60_69   JANSS    121
26                AT    Age60_69     MOD    121
27                AT    Age70_79     COM    121
28                AT    Age70_79   JANSS    121
29                AT    Age70_79     MOD    121
30                AT      Age80+     COM    121
31                AT      Age80+   JANSS    121
32                AT      Age80+     MOD    121
33                AT      Age<18     COM    121
34                AT      Age<18   JANSS    121
35                AT      Age<18     MOD    121
36                BE         ALL     COM    121
37                BE         ALL   JANSS    121
38                BE         ALL     MOD    121
39                BE    Age18_24     COM    120
40                BE    Age18_24     MOD    115
41                BE    Age18_24   JANSS    100
42                BE    Age25_49     COM    120
43                BE    Age25_49     MOD    115
44                BE    Age25_49   JANSS    100
45                BE    Age50_59     COM    120
46                BE    Age50_59     MOD    115
47                BE    Age50_59   JANSS    100
48                BE    Age60_69     COM    120
49                BE    Age60_69     MOD    115
50                BE    Age60_69   JANSS    100
51                BE    Age70_79     COM    120
52                BE    Age70_79     MOD    115
53                BE    Age70_79   JANSS    100
54                BE      Age80+     COM    120
55                BE      Age80+     MOD    115
56                BE      Age80+   JANSS    100
57                BE      Age<18     COM    120
58                BE      Age<18     MOD    115
59                BE      Age<18   JANSS    100
60                BE      AgeUNK     COM    120
61                BE      AgeUNK     MOD    115
62                BE      AgeUNK   JANSS    100
63                BE         HCW     COM    120
64                BE         HCW     MOD    115
65                BE         HCW   JANSS    100
66                BE        LTCF     COM    120
67                BE        LTCF     MOD    115
68                BE        LTCF   JANSS    100
69                BG         ALL     COM    121
70                BG         ALL     MOD    120
71                BG         ALL   JANSS    105
72                BG    Age18_24     COM    120
73                BG    Age18_24     MOD    120
74                BG    Age18_24   JANSS    105
75                BG    Age25_49     COM    120
76                BG    Age25_49     MOD    120
77                BG    Age25_49   JANSS    105
78                BG    Age50_59     COM    120
79                BG    Age50_59     MOD    120
80                BG    Age50_59   JANSS    105
81                BG    Age60_69     COM    120
82                BG    Age60_69     MOD    120
83                BG    Age60_69   JANSS    105
84                BG    Age70_79     COM    120
85                BG    Age70_79     MOD    120
86                BG    Age70_79   JANSS    105
87                BG      Age80+     COM    120
88                BG      Age80+     MOD    120
89                BG      Age80+   JANSS    105
90                BG      Age<18     COM     97
91                BG      Age<18   JANSS     97
92                BG      Age<18     MOD     97
93                BG      AgeUNK     COM    120
94                BG      AgeUNK     MOD    120
95                BG      AgeUNK   JANSS    105
96                BG         HCW     COM    120
97                BG         HCW     MOD    120
98                BG         HCW   JANSS    105
99                BG        LTCF     COM    120
100               BG        LTCF     MOD    120
101               BG        LTCF   JANSS    105
102               CY         ALL     COM    120
103               CY         ALL     MOD    108
104               CY         ALL   JANSS    101
105               CY      Age0_4     COM      9
106               CY      Age0_4   JANSS      7
107               CY    Age10_14     COM     89
108               CY    Age10_14   JANSS     87
109               CY    Age10_14     MOD     81
110               CY    Age15_17     COM    106
111               CY    Age15_17   JANSS     95
112               CY    Age15_17     MOD     92
113               CY    Age18_24     COM    120
114               CY    Age18_24   JANSS     99
115               CY    Age18_24     MOD     99
116               CY    Age25_49     COM    120
117               CY    Age25_49     MOD    105
118               CY    Age25_49   JANSS     99
119               CY    Age50_59     COM    120
120               CY    Age50_59     MOD    103
121               CY    Age50_59   JANSS     99
122               CY      Age5_9     COM     69
123               CY      Age5_9   JANSS      7
124               CY    Age60_69     COM    120
125               CY    Age60_69     MOD    105
126               CY    Age60_69   JANSS     99
127               CY    Age70_79     COM    120
128               CY    Age70_79     MOD    104
129               CY    Age70_79   JANSS     99
130               CY      Age80+     COM    120
131               CY      Age80+     MOD    105
132               CY      Age80+   JANSS     98
133               CY      AgeUNK     COM      8
134               CY         HCW     COM    120
135               CY         HCW     MOD    102
136               CY         HCW   JANSS     99
137               CY        LTCF     COM    120
138               CY        LTCF     MOD    104
139               CY        LTCF   JANSS     99
140               CZ         ALL     COM    121
141               CZ         ALL     MOD    120
142               CZ         ALL   JANSS    111
143               CZ      Age0_4     COM     27
144               CZ    Age10_14     COM    106
145               CZ    Age10_14     MOD     90
146               CZ    Age10_14   JANSS      1
147               CZ    Age15_17     COM    120
148               CZ    Age15_17     MOD    105
149               CZ    Age15_17   JANSS     15
150               CZ    Age18_24     COM    121
151               CZ    Age18_24     MOD    112
152               CZ    Age18_24   JANSS    111
153               CZ    Age25_49     COM    121
154               CZ    Age25_49     MOD    120
155               CZ    Age25_49   JANSS    111
156               CZ    Age50_59     COM    121
157               CZ    Age50_59     MOD    116
158               CZ    Age50_59   JANSS    107
159               CZ      Age5_9     COM     73
160               CZ    Age60_69     COM    121
161               CZ    Age60_69     MOD    116
162               CZ    Age60_69   JANSS     96
163               CZ    Age70_79     COM    121
164               CZ    Age70_79     MOD    109
165               CZ    Age70_79   JANSS     75
166               CZ      Age80+     COM    121
167               CZ      Age80+     MOD    105
168               CZ      Age80+   JANSS     60
169               CZ      Age<18     COM    120
170               CZ      Age<18     MOD    110
171               CZ      Age<18   JANSS     15
172               CZ         HCW     COM    121
173               CZ         HCW     MOD    113
174               CZ         HCW   JANSS     83
175               CZ        LTCF     COM    116
176               CZ        LTCF     MOD    100
177               CZ        LTCF   JANSS     40
178               DK         ALL     COM    123
179               DK         ALL     MOD    118
180               DK         ALL   JANSS    106
181               DK      Age0_4     COM     11
182               DK      Age0_4     MOD      4
183               DK    Age10_14     COM     99
184               DK    Age10_14     MOD     34
185               DK    Age10_14   JANSS      2
186               DK    Age15_17     COM    110
187               DK    Age15_17     MOD     53
188               DK    Age15_17   JANSS      5
189               DK    Age18_24     COM    121
190               DK    Age18_24     MOD    106
191               DK    Age18_24   JANSS     79
192               DK    Age25_49     COM    123
193               DK    Age25_49     MOD    116
194               DK    Age25_49   JANSS    100
195               DK    Age50_59     COM    122
196               DK    Age50_59     MOD    113
197               DK    Age50_59   JANSS     59
198               DK      Age5_9     COM     73
199               DK      Age5_9     MOD      3
200               DK    Age60_69     COM    120
201               DK    Age60_69     MOD    115
202               DK    Age60_69   JANSS     44
203               DK    Age70_79     COM    118
204               DK    Age70_79     MOD    108
205               DK    Age70_79   JANSS     22
206               DK      Age80+     COM    116
207               DK      Age80+     MOD    111
208               DK      Age80+   JANSS      8
209               DK         HCW     COM    123
210               DK         HCW     MOD    118
211               DK         HCW   JANSS    106
212               DK        LTCF     COM    123
213               DK        LTCF     MOD    118
214               DK        LTCF   JANSS    106
215               EE         ALL     COM    121
216               EE         ALL     MOD    118
217               EE         ALL   JANSS    105
218               EE    Age18_24     COM    121
219               EE    Age18_24     MOD    118
220               EE    Age18_24   JANSS    105
221               EE    Age25_49     COM    121
222               EE    Age25_49     MOD    118
223               EE    Age25_49   JANSS    105
224               EE    Age50_59     COM    121
225               EE    Age50_59     MOD    118
226               EE    Age50_59   JANSS    105
227               EE    Age60_69     COM    121
228               EE    Age60_69     MOD    118
229               EE    Age60_69   JANSS    105
230               EE    Age70_79     COM    121
231               EE    Age70_79     MOD    118
232               EE    Age70_79   JANSS    105
233               EE      Age80+     COM    121
234               EE      Age80+     MOD    118
235               EE      Age80+   JANSS    105
236               EE      Age<18     COM    116
237               EE      Age<18     MOD    103
238               EE      Age<18   JANSS    100
239               EE      AgeUNK     COM    121
240               EE      AgeUNK     MOD    118
241               EE      AgeUNK   JANSS    105
242               EE         HCW     COM     26
243               EE         HCW     MOD     21
244               EE         HCW   JANSS      6
245               EE        LTCF     COM     25
246               EE        LTCF     MOD     22
247               EE        LTCF   JANSS      7
248               EL    1_Age60+     COM    121
249               EL    1_Age60+   JANSS    121
250               EL    1_Age60+     MOD    121
251               EL    1_Age<60     COM    121
252               EL    1_Age<60   JANSS    121
253               EL    1_Age<60     MOD    121
254               EL         ALL     COM    121
255               EL         ALL   JANSS    121
256               EL         ALL     MOD    121
257               EL      Age0_4     COM    121
258               EL      Age0_4   JANSS    121
259               EL      Age0_4     MOD    121
260               EL    Age10_14     COM    121
261               EL    Age10_14   JANSS    121
262               EL    Age10_14     MOD    121
263               EL    Age15_17     COM    121
264               EL    Age15_17   JANSS    121
265               EL    Age15_17     MOD    121
266               EL    Age18_24     COM    121
267               EL    Age18_24   JANSS    121
268               EL    Age18_24     MOD    121
269               EL    Age25_49     COM    121
270               EL    Age25_49   JANSS    121
271               EL    Age25_49     MOD    121
272               EL    Age50_59     COM    121
273               EL    Age50_59   JANSS    121
274               EL    Age50_59     MOD    121
275               EL      Age5_9     COM    121
276               EL      Age5_9   JANSS    121
277               EL      Age5_9     MOD    121
278               EL    Age60_69     COM    121
279               EL    Age60_69   JANSS    121
280               EL    Age60_69     MOD    121
281               EL    Age70_79     COM    121
282               EL    Age70_79   JANSS    121
283               EL    Age70_79     MOD    121
284               EL      Age80+     COM    121
285               EL      Age80+   JANSS    121
286               EL      Age80+     MOD    121
287               EL      Age<18     COM    121
288               EL      Age<18   JANSS    121
289               EL      Age<18     MOD    121
290               EL      AgeUNK     COM    121
291               EL      AgeUNK   JANSS    121
292               EL      AgeUNK     MOD    121
293               EL         HCW     COM    121
294               EL         HCW   JANSS    121
295               EL         HCW     MOD    121
296               EL        LTCF     COM     93
297               EL        LTCF   JANSS     28
298               ES         ALL     COM    120
299               ES         ALL   JANSS    120
300               ES         ALL     MOD    120
301               ES      Age0_4     COM    120
302               ES      Age0_4   JANSS    120
303               ES      Age0_4     MOD    120
304               ES    Age10_14     COM    120
305               ES    Age10_14   JANSS    120
306               ES    Age10_14     MOD    120
307               ES    Age15_17     COM    120
308               ES    Age15_17   JANSS    120
309               ES    Age15_17     MOD    120
310               ES    Age18_24     COM    120
311               ES    Age18_24   JANSS    120
312               ES    Age18_24     MOD    120
313               ES    Age25_49     COM    120
314               ES    Age25_49   JANSS    120
315               ES    Age25_49     MOD    120
316               ES    Age50_59     COM    120
317               ES    Age50_59   JANSS    120
318               ES    Age50_59     MOD    120
319               ES      Age5_9     COM    120
320               ES      Age5_9   JANSS    120
321               ES      Age5_9     MOD    120
322               ES    Age60_69     COM    120
323               ES    Age60_69   JANSS    120
324               ES    Age60_69     MOD    120
325               ES    Age70_79     COM    120
326               ES    Age70_79   JANSS    120
327               ES    Age70_79     MOD    120
328               ES      Age80+     COM    120
329               ES      Age80+   JANSS    120
330               ES      Age80+     MOD    120
331               ES      Age<18     COM    120
332               ES      Age<18   JANSS    120
333               ES      Age<18     MOD    120
334               ES      AgeUNK     COM    120
335               ES      AgeUNK   JANSS    120
336               ES      AgeUNK     MOD    120
337               ES         HCW     COM    120
338               ES         HCW   JANSS    120
339               ES         HCW     MOD    120
340               ES        LTCF     COM    120
341               ES        LTCF   JANSS    120
342               ES        LTCF     MOD    120
343               FI         ALL     COM   2928
344               FI         ALL   JANSS   2928
345               FI         ALL     MOD   2928
346               FI      Age0_4     COM   2928
347               FI      Age0_4   JANSS   2928
348               FI      Age0_4     MOD   2928
349               FI    Age10_14     COM   2928
350               FI    Age10_14   JANSS   2928
351               FI    Age10_14     MOD   2928
352               FI    Age15_17     COM   2928
353               FI    Age15_17   JANSS   2928
354               FI    Age15_17     MOD   2928
355               FI    Age18_24     COM   2928
356               FI    Age18_24   JANSS   2928
357               FI    Age18_24     MOD   2928
358               FI    Age25_49     COM   2928
359               FI    Age25_49   JANSS   2928
360               FI    Age25_49     MOD   2928
361               FI    Age50_59     COM   2928
362               FI    Age50_59   JANSS   2928
363               FI    Age50_59     MOD   2928
364               FI      Age5_9     COM   2928
365               FI      Age5_9   JANSS   2928
366               FI      Age5_9     MOD   2928
367               FI    Age60_69     COM   2928
368               FI    Age60_69   JANSS   2928
369               FI    Age60_69     MOD   2928
370               FI    Age70_79     COM   2928
371               FI    Age70_79   JANSS   2928
372               FI    Age70_79     MOD   2928
373               FI      Age80+     COM   2928
374               FI      Age80+   JANSS   2928
375               FI      Age80+     MOD   2928
376               FI      Age<18     COM   2928
377               FI      Age<18   JANSS   2928
378               FI      Age<18     MOD   2928
379               FI      AgeUNK     COM   2928
380               FI      AgeUNK   JANSS   2928
381               FI      AgeUNK     MOD   2928
382               FR         ALL     COM    121
383               FR         ALL   JANSS    121
384               FR         ALL     MOD    121
385               HR         ALL     COM     96
386               HR         ALL     MOD     95
387               HR         ALL   JANSS     89
388               HR      Age0_4     COM     96
389               HR      Age0_4     MOD     95
390               HR      Age0_4   JANSS     89
391               HR    Age10_14     COM     96
392               HR    Age10_14     MOD     95
393               HR    Age10_14   JANSS     89
394               HR    Age15_17     COM     96
395               HR    Age15_17     MOD     95
396               HR    Age15_17   JANSS     89
397               HR    Age18_24     COM     96
398               HR    Age18_24     MOD     95
399               HR    Age18_24   JANSS     89
400               HR    Age25_49     COM     96
401               HR    Age25_49     MOD     95
402               HR    Age25_49   JANSS     89
403               HR    Age50_59     COM     96
404               HR    Age50_59     MOD     95
405               HR    Age50_59   JANSS     89
406               HR      Age5_9     COM     96
407               HR      Age5_9     MOD     95
408               HR      Age5_9   JANSS     89
409               HR    Age60_69     COM     96
410               HR    Age60_69     MOD     95
411               HR    Age60_69   JANSS     89
412               HR    Age70_79     COM     96
413               HR    Age70_79     MOD     95
414               HR    Age70_79   JANSS     89